### PR TITLE
Zy/952 evaluate numeric disable

### LINKED ISSUE #952: EVALUATE: If the target variable is numeric then disable evaluations
## Description

Current evaluations are focused on classification rather than regression.

If the target variable is numeric then disable the evaluation `Model` check boxes and ensure none are ticked.

If the user taps the BUILD button then when the target is numeric popup a message to say that the evaluation of regression models is not currently available.

Eventually we will need to add regression evaluations.

### PR DESCRIPTION
**Pull request by zheyxu**
# Pull Request Details

## What issue does this PR address

- EVALUATE: If the target variable is numeric then disable evaluations

- Link to associated issue: #952 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [x] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [x] Tested on device:
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added software engineer reviewer
- [ ] Approved by one software engineer reviewer
- [ ] Approved by team leader

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

File: lib/features/evaluate/config.dart [hunk 1]
```diff
@@ -335,119 +342,136 @@ class EvaluateConfigState extends ConsumerState<EvaluateConfig> {
...
-                  ref: ref,
-                );
-
-                await ref.read(evaluatePageControllerProvider).animateToPage(
-                      // Index of the second page.
-                      1,
-                      duration: const Duration(milliseconds: 300),
-                      curve: Curves.easeInOut,
-                    );
+                if (numericDisabled) {
```
Comment (gjwgit) [inline lib/features/evaluate/config.dart:345]: Why not put the test earlier?

**Review by gjwgit — APPROVED** [review]
