### PR TITLE
zy/677_evaluate_error_matrix_neural

### LINKED ISSUE #677: EVALUATE: Review pred_ra and prob_ra for Neural
The building of a predictive model for classification with nnet and neural is failing, predicting all in one class or else NA. 

V5 only implements nnet but also predicts all 0:

```
Error matrix for the Neural Net model on audit.csv [validate] (counts):

      Predicted
Actual   0 Error
     0 226     0
     1  64   100

Error matrix for the Neural Net model on audit.csv [validate] (proportions):

      Predicted
Actual    0 Error
     0 77.9     0
     1 22.1   100

Overall error: -77.9%, Averaged class error: 50%
```

### PR DESCRIPTION
**Pull request by zheyxu**
# Pull Request Details

## What issue does this PR address

- EVALUATE: Error Matrix for Neural

- Link to associated issue: #677

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [x] Pre-exisiting lint errors noted: [HERE]
- [x] Integration test `make qtest.tmp` screenshot included in issue
- [x] Tested on device:
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added two reviewers

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

File: assets/r/evaluate_nnet.R [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+# References:
+#
+# @williams:2017:essentials Chapter 7.
+# https://survivor.togaware.com/datascience/dtrees.html
+# https://survivor.togaware.com/datascience/rpart.html
+# https://survivor.togaware.com/datascience/ for further details.
+
+library(rattle)
+
+print("Error matrix for the Linear model (counts)")
```
Comment (gjwgit) [inline assets/r/evaluate_nnet.R:38]: ??LINEAR??

File: assets/r/evaluate_nnet.R [hunk 2]
```diff
@@ -0,0 +1,50 @@
+# Generate error matrix of model nnet.
```
Comment (gjwgit) [inline assets/r/evaluate_nnet.R:1]: Is this generating the error matrix or the predictions for evaluation?

**Review by gjwgit — COMMENTED** [review]
Please use the style that discussed

**Review by gjwgit — COMMENTED** [review]
Need to be careful re style and commentary .
