### PR TITLE
zy/946 fix normasized neuralnet

### LINKED ISSUE #946: BUG: Fix building normalised neural network
If I normalise the attribute "temp_3pm" to  [0,1] and use the new attribute "R01_temp_3pm" as the target, Rattle will produce an error. The current version only works if I do not normalise the target attribute, but this is incorrect.

### PR DESCRIPTION
**Pull request by zheyxu**
# Pull Request Details

## What issue does this PR address

- BUG: Fix building normalised neural network

- Link to associated issue: #946 

## Checklist

Complete the check-list below to ensure your branch is ready for PR.

Flutter Style Guide: https://survivor.togaware.com/gnulinux/flutter-style.html

- [x] Screenshots included in linked issue
- [x] Changes adhere to the style and coding guideline
- [x] No confidential information
- [x] No duplicated content
- [x] No lint check errors related to your changes (`make prep` or `flutter analyze lib`)
- [x] Pre-exisiting lint errors noted: [HERE]
- [ ] Integration test `make qtest.tmp` screenshot included in issue
- [x] Tested on device:
  - [ ] Linux
  - [x] MacOS
  - [ ] Windows
- [x] Added software engineer reviewer
- [ ] Approved by one software engineer reviewer
- [ ] Approved by team leader

## Finalising

Once PR discussion is complete and reviewers have approved:

- [ ] Merge dev into the branch
- [ ] Resolve any conflicts
- [ ] Add one line summary into CHANGELOG.md
- [ ] Bump appropriate version number in pubspec.yaml
- [ ] Push to git repository and review
- [ ] Merge PR into dev (gjwgit)

### CODE REVIEW

File: assets/r/packages.R [hunk 1]
```diff
@@ -106,6 +106,7 @@ pkgs <- c(
   'lubridate',
   'magrittr',
   'mice',
```
Comment (gjwgit) [inline assets/r/packages.R:108]: Where is ModelMetrics used?

Comment (gjwgit) [reply assets/r/packages.R:108]: Do we need to add caret instead? Though that probably gets included as a dependency to another package we depend on.

Comment (zheyxu) [reply assets/r/packages.R:108]: Hi @gjwgit, ModelMetrics is used for `caret depends on ModelMetrics`. caret is used in assets/r/model_build_neuralnet.R

Comment (gjwgit) [reply assets/r/packages.R:108]: Thus ModelMetrics should not need to be listed because it should be automatically installed when package caret gets installed. Thus I don;t think it needs to be listed in packages.R? Was there a situation that says ModelMetric is missing?

Comment (zheyxu) [reply assets/r/packages.R:108]: If ModelMetrics was not listed, it raises the issue

```
dmy_target <- caret::dummyVars(~ ., data = tds[target])
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘ModelMetrics’ fix the error
```

Comment (gjwgit) [reply assets/r/packages.R:108]: Okay. It should have been installed when caret gets installed. What happens when you do in R `install.packages('caret')`

Comment (gjwgit) [reply assets/r/packages.R:108]: I might go ahead with the explicit caret:: but leave the ModelMetrics out for now, thinking it might be a bad install of R packages.

**Review by gjwgit — APPROVED** [review]
